In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

df=pd.read_csv('https://raw.githubusercontent.com/aniruddhachoudhury/Red-Wine-Quality/master/winequality-red.csv')

In [2]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
df.shape

(1599, 12)

In [4]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [6]:
## Independent And Dependent Features
X=df.iloc[:,:-1]  ## drop quality
Y=df.iloc[:,-1]  ## retain quality

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.33, random_state=10)

In [8]:
X_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
151             9.2             0.520         1.00             3.4      0.610   
514            10.5             0.510         0.64             2.4      0.107   
461             8.3             0.615         0.22             2.6      0.087   
1193            6.4             0.885         0.00             2.3      0.166   
976             7.2             0.410         0.30             2.1      0.083   
...             ...               ...          ...             ...        ...   
1393            8.0             0.520         0.25             2.0      0.078   
1344           11.5             0.420         0.48             2.6      0.077   
527             7.0             0.380         0.49             2.5      0.097   
1149           10.0             0.350         0.47             2.0      0.061   
1289            7.0             0.600         0.30             4.5      0.068   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
151                  32.0                  69.0  0.99960  2.74       2.00   
514                   6.0                  15.0  0.99730  3.09       0.66   
461                   6.0                  19.0  0.99820  3.26       0.61   
1193                  6.0                  12.0  0.99551  3.56       0.51   
976                  35.0                  72.0  0.99700  3.44       0.52   
...                   ...                   ...      ...   ...        ...   
1393                 19.0                  59.0  0.99612  3.30       0.48   
1344                  8.0                  20.0  0.99852  3.09       0.53   
527                  33.0                  85.0  0.99620  3.39       0.77   
1149                  6.0                  11.0  0.99585  3.23       0.52   
1289                 20.0                 110.0  0.99914  3.30       1.17   

      alcohol  
151       9.4  
514      11.8  
461       9.3  
1193     10.8  
976       9.4  
...       ...  
1393     10.2  
1344     11.0  
527      11.4  
1149     12.0  
1289     10.2  

[1071 rows x 11 columns]

In [9]:
X_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1518            7.4             0.470         0.46             2.2      0.114   
1246            7.4             0.740         0.07             1.7      0.086   
544            14.3             0.310         0.74             1.8      0.075   
1343            7.5             0.510         0.02             1.7      0.084   
428             9.1             0.520         0.33             1.3      0.070   
...             ...               ...          ...             ...        ...   
774             7.9             0.400         0.30             1.8      0.157   
1150            8.2             0.330         0.32             2.8      0.067   
381            13.7             0.415         0.68             2.9      0.085   
1500            7.5             0.725         0.04             1.5      0.076   
860             7.2             0.620         0.06             2.7      0.077   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1518                  7.0                  20.0  0.99647  3.32       0.63   
1246                 15.0                  48.0  0.99502  3.12       0.48   
544                   6.0                  15.0  1.00080  2.86       0.79   
1343                 13.0                  31.0  0.99538  3.36       0.54   
428                   9.0                  30.0  0.99780  3.24       0.60   
...                   ...                   ...      ...   ...        ...   
774                   2.0                  45.0  0.99727  3.31       0.91   
1150                  4.0                  12.0  0.99473  3.30       0.76   
381                  17.0                  43.0  1.00140  3.06       0.80   
1500                  8.0                  15.0  0.99508  3.26       0.53   
860                  15.0                  85.0  0.99746  3.51       0.54   

      alcohol  
1518     10.5  
1246     10.0  
544       8.4  
1343     10.5  
428       9.3  
...       ...  
774       9.5  
1150     12.8  
381      10.0  
1500      9.6  
860       9.5  

[528 rows x 11 columns]

In [10]:
y_train

151     4
514     7
461     5
1193    5
976     5
       ..
1393    5
1344    5
527     6
1149    6
1289    5
Name: quality, Length: 1071, dtype: int64

In [11]:
## Standardize or feature scaling the datasets  using std scaler mena=0 and unit variance /std devation 1
from sklearn.preprocessing import StandardScaler
print('*** Standarization using Std Scaler mean =0 and variance is unity *****')
scaler=StandardScaler()
X_train1=scaler.fit_transform(X_train)  
print(scaler.mean_)

X_test1=scaler.transform(X_test)
print('*** SVC using  Std Scaler ***')
print('X train using stdscaler is:',X_train1)
print('X test using stdscaler is:',X_test1)
from sklearn.svm import SVC
model=SVC()
model.fit(X_train1,y_train)
print('F1 score:',model.score(X_train1,y_train))
y_pred_stdscaler=model.predict(X_test1)
print('y pred:',y_pred_stdscaler)


*** Standarization using Std Scaler mean =0 and variance is unity *****
[ 8.34920635  0.52628385  0.2754155   2.58225957  0.0897479  16.07656396
 47.20074697  0.99683377  3.30894491  0.66496732 10.38215064]
*** SVC using  Std Scaler ***
X train using stdscaler is: [[ 0.48509824 -0.03513851  3.72747792 ... -3.67945073  7.24826008
  -0.93540053]
 [ 1.22632112 -0.09105729  1.87553098 ... -1.41594906 -0.02696895
   1.35036011]
 [-0.02805606  0.49608995 -0.28507379 ... -0.31653397 -0.29843272
  -1.03064055]
 ...
 [-0.76927893 -0.8180015   1.10388642 ...  0.52419522  0.57025134
   0.9694    ]
 [ 0.9412354  -0.98575786  1.00100048 ... -0.5105484  -0.78706751
   1.54084016]
 [-0.76927893  0.41221177  0.12646997 ... -0.05784806  2.7419615
  -0.17348032]]
X test using stdscaler is: [[-0.54121035 -0.31473244  0.94955751 ...  0.07149489 -0.18984721
   0.11223976]
 [-0.54121035  1.19507477 -1.05671835 ... -1.22193464 -1.00423852
  -0.36396037]
 [ 3.3929726  -1.209433    2.38996068 ... -2.90339302  

In [12]:
## Performance Metrics

from sklearn.metrics import accuracy_score
print('*** Performnace Metrics using Std Scaler ***')

accuracy_stdscaler=accuracy_score(y_test,y_pred_stdscaler)
print('Accuracy using Std scaler for SVC  is:',accuracy_stdscaler)      

*** Performnace Metrics using Std Scaler ***
Accuracy using Std scaler for SVC  is: 0.6079545454545454


#### MinMAx Scaler:
* This estimator scales and translates each feature individually such that it is in the given range on the training set, e.g. between zero and one so that the maximum absolute value of each feature is scaled to unit size. This can be achieved using MinMaxScaler or MaxAbsScaler, respectively.
* This transformation is often used as an alternative to zero mean, unit variance scaling.
* The motivation to use this scaling include robustness to very small standard deviations of features and preserving zero entries in sparse data.

In [13]:
### imprort minmax scaler from scikit preprocessing class
## fit and transform X tain,
### transform Xtest
## find the values of Performnace metrices

In [14]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)

print('X train using min max scaler is:',X_train_minmax)
X_test_minmax=min_max_scaler.transform(X_test)
print('X test using min max scaler is:',X_test_minmax)

from sklearn.svm import SVC
model1=SVC()
model1.fit(X_train_minmax,y_train)

print('F1 score:',model1.score(X_train_minmax,y_train))
y_pred_minmax=model1.predict(X_test_minmax)
print('y_predicated :',y_pred_minmax)

X train using min max scaler is: [[0.40707965 0.2739726  1.         ... 0.         1.         0.15384615]
 [0.52212389 0.26712329 0.64       ... 0.27559055 0.19760479 0.52307692]
 [0.32743363 0.3390411  0.22       ... 0.40944882 0.16766467 0.13846154]
 ...
 [0.21238938 0.17808219 0.49       ... 0.51181102 0.26347305 0.46153846]
 [0.47787611 0.15753425 0.47       ... 0.38582677 0.11377246 0.55384615]
 [0.21238938 0.32876712 0.3        ... 0.44094488 0.50299401 0.27692308]]
X test using min max scaler is: [[0.24778761 0.23972603 0.46       ... 0.45669291 0.17964072 0.32307692]
 [0.24778761 0.42465753 0.07       ... 0.2992126  0.08982036 0.24615385]
 [0.85840708 0.13013699 0.74       ... 0.09448819 0.2754491  0.        ]
 ...
 [0.80530973 0.20205479 0.68       ... 0.2519685  0.28143713 0.24615385]
 [0.25663717 0.41438356 0.04       ... 0.40944882 0.11976048 0.18461538]
 [0.2300885  0.34246575 0.06       ... 0.60629921 0.1257485  0.16923077]]
F1 score: 0.6517273576097106
y_predicated : [6 

In [15]:
## Performance Metrics

from sklearn.metrics import accuracy_score
print('*** Performnace Metrics using Min-Max Scaler ***')

accuracy_minmax=accuracy_score(y_test,y_pred_minmax)
print('Accuracy using min max scaler for SVC  is:',accuracy_minmax) 

*** Performnace Metrics using Min-Max Scaler ***
Accuracy using min max scaler for SVC  is: 0.5814393939393939


#### Max Abs Scaler
* MaxAbsScaler works in a very similar fashion, but scales in a way that the training data lies within the range [-1, 1] by dividing through the largest maximum value in each feature. 
* It is meant for data that is already centered at zero or sparse data.

#### imprort max absscaler from scikit preprocessing class
* fit and transform X train,
* transform Xtest
* find the values of Performnace metrices

In [16]:
from sklearn.preprocessing import MaxAbsScaler
max_absscaler = MaxAbsScaler()
X_train_maxabs =max_absscaler.fit_transform(X_train)

print('X train using  max abs scaler is:',X_train_maxabs)
X_test_maxabs=max_absscaler.transform(X_test)
print('X test using  max abs scaler is:',X_test_maxabs)

from sklearn.svm import SVC
model2=SVC()
model2.fit(X_train_maxabs,y_train)
print('F1 score:',model2.score(X_train_maxabs,y_train))
y_pred_maxabs=model2.predict(X_test_maxabs)
print('y_predicated :',y_pred_maxabs)

X train using  max abs scaler is: [[0.57861635 0.32911392 1.         ... 0.68329177 1.         0.63087248]
 [0.66037736 0.32278481 0.64       ... 0.77057357 0.33       0.79194631]
 [0.52201258 0.38924051 0.22       ... 0.81296758 0.305      0.62416107]
 ...
 [0.44025157 0.24050633 0.49       ... 0.84538653 0.385      0.76510067]
 [0.62893082 0.22151899 0.47       ... 0.80548628 0.26       0.80536913]
 [0.44025157 0.37974684 0.3        ... 0.82294264 0.585      0.68456376]]
X test using  max abs scaler is: [[0.46540881 0.29746835 0.46       ... 0.82793017 0.315      0.70469799]
 [0.46540881 0.46835443 0.07       ... 0.77805486 0.24       0.67114094]
 [0.89937107 0.19620253 0.74       ... 0.71321696 0.395      0.56375839]
 ...
 [0.86163522 0.26265823 0.68       ... 0.76309227 0.4        0.67114094]
 [0.47169811 0.45886076 0.04       ... 0.81296758 0.265      0.6442953 ]
 [0.45283019 0.39240506 0.06       ... 0.87531172 0.27       0.63758389]]
F1 score: 0.6069094304388422
y_predicated : [

In [17]:
print('*** Performnace Metrics using Min-Max Scaler ***')

accuracy_maxabs=accuracy_score(y_test,y_pred_maxabs)
print('Accuracy using min max scaler for SVC  is:',accuracy_maxabs) 

*** Performnace Metrics using Min-Max Scaler ***
Accuracy using min max scaler for SVC  is: 0.5662878787878788


In [18]:
#### Observations
* Stdscaler provides good accuracy compare to Min max and max absscaler.The values are 0.60 ,0.58, 0.56 respectively
* further F1 score of STD scaler is 0.68 as compared to Minmax and Max abosoute scaler which are 0.65,0.60  respectively

SyntaxError: invalid syntax (<ipython-input-18-f03615754462>, line 2)

#### 2. Hyperparameter tuning using Gridsearch CV
* Hyperparameter tuning is done to increase the efficiency of a model by tuning the parameters of the neural network.
* Some scikit-learn APIs like GridSearchCV and RandomizedSearchCV are used to perform hyper parameter tuning. 
* SVM also has some hyper-parameters (like what C or gamma values to use) and finding optimal hyper-parameter is a very hard task to solve.
* But it can be found by just trying all combinations and see what parameters work best. 
* The main idea behind it is to create a grid of hyper-parameters and just try all of their combinations (hence, this method is called Gridsearch, But don’t worry! we don’t have to do it manually because Scikit-learn has this functionality built-in with GridSearchCV.
* GridSearchCV takes a dictionary that describes the parameters that could be tried on a model to train it. 
* The grid of parameters is defined as a dictionary, where the keys are the parameters and the values are the settings to be tested.

In [ ]:

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
print(classification_report(y_test, y_pred_stdscaler))

In [ ]:
##Notice that recall and precision for class 2,3 and 8 are always 0. 
## It means that the classifier is always classifying everything into a single class i.e class 5,6,7! 
##This means our model needs to have its parameters tuned.
##GridSearchCV is that it is a meta-estimator. It takes an estimator like SVC and creates a new estimator,
### that behaves exactly the same – in this case, like a classifier. 
### You should add refit=True and choose verbose to whatever number you want, the higher the number, the more verbose (verbose just means the text output describing the process).

In [ ]:
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']} 
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(X_train, y_train)

#### What fit does is a bit more involved than usual. 
#### First, it runs the same loop with cross-validation, to find the best parameter combination. 
#### Once it has the best combination, it runs fit again on all data passed to fit (without cross-validation), to build a single new model using the best parameter setting.
#### You can inspect the best parameters found by GridSearchCV in the best_params_ attribute, and the best estimator in the best_estimator_ attribute: 

In [ ]:
# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

In [ ]:
##-run predictions and see a classification report on this grid object just like you would with a normal model.

grid_predictions = grid.predict(X_test)
  
# print classification report
print(classification_report(y_test, grid_predictions))

#### 3. YOU HVAE TO IMPLEMENT SVR(ADDIMISSOIN_PREDICTION)

In [ ]:
df1=pd.read_csv('https://raw.githubusercontent.com/srinivasav22/Graduate-Admission-Prediction/master/Admission_Predict_Ver1.1.csv')

In [ ]:
df1.head()

In [ ]:
df1.shape

In [ ]:
df1.info()

In [ ]:
df1.describe().T

In [ ]:
df1.isnull().sum()

In [ ]:
sns.set(rc={'figure.figsize':(10,8)})

sns.heatmap(df1.corr(),annot=True)

In [ ]:
## Independent And Dependent Features
X2=df1.iloc[:,:-1]  ## drop quality
Y2=df1.iloc[:,-1]  ## retain quality
print(X2)
print(Y2)

In [ ]:
from sklearn.model_selection import train_test_split
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, Y2, test_size=0.33, random_state=10)

In [ ]:
## Standardize or feature scaling the datasets  using std scaler mena=0 and unit variance /std devation 1
from sklearn.preprocessing import StandardScaler
print('*** Standarization using Std Scaler mean =0 and variance is unity *****')
scaler=StandardScaler()
X2_train=scaler.fit_transform(X2_train)  
print(scaler.mean_)
X2_test=scaler.transform(X2_test)

print('*** SVRusing  Std Scaler ***')
print('X train using stdscaler is:',X2_train)
print('X test using stdscaler is:',X2_test)

from sklearn.svm import SVR
# create the model object
regressor = SVR(kernel = 'rbf')
# fit the model on the data
regressor.fit(X2_train,y2_train)
y_pred_svr=regressor.predict(X2_test)

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print(mean_squared_error(y2_test,y_pred_svr))
print(mean_absolute_error(y2_test,y_pred_svr))
print(np.sqrt(mean_squared_error(y2_test,y_pred_svr)))

score=r2_score(y2_test,y_pred_svr)
print(score)
1-(1-score)*(len(y2_test)-1)/(len(y2_test)-X2_test.shape[1]-1)